export const PAGE_SLUG_SEGMENT_REGEX = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

export const RESERVED_PAGE_SLUGS = [
  'dogadanja',
  'galerija',
  'vijesti',
  'obavijesti',
  'dokumenti',
  'kontakt',
  'prijava-problema',
  'opcina',
  'naselja',
  'udruge',
  'organizacija',
  'usluge',
  'izbori',
  'izjava-o-pristupacnosti',
  'privatnost',
  'uvjeti-koristenja',
  'sigurnost',
  'transparentnost',
  'vijece',
  'nacelnik',
  'skola',
  'zupa',
  'dozivi-opcinu',
  'odvoz-otpada',
  'natjecaji',
  'newsletter',
  'api',
] as const;
